### ISSUE TITLE
Best Architecture Extraction after the search is complete.

### ISSUE THREAD

**Issue by DRealArun** [negrinho/deep_architect_legacy#2]
Is there a way, I can get the best architecture at the end of the search process so that I can retrain it ?

**Comment by negrinho** [comment]
It depends on what you mean by retrieving the architecture. After compilation, you are just dealing with Tensorflow graphs, so whatever functionality exists to store a Tensorflow computational graph can be used in this case. More specifically, [here](https://github.com/negrinho/deep_architect/blob/master/darch/evaluators.py#L70), `pred` is just the last tensorflow op for the network; `x` is the placeholder for feeding the data. Another possibility is to take the unspecified search space and assign values the hyperparameters with [this method](https://github.com/negrinho/deep_architect/blob/master/darch/searchers.py#L35) and then compile and do whatever you want with the Tensorflow graph it outputs. The values for the hyperparameters will come from the searcher.

**Comment by DRealArun** [comment]
Thanks for the detailed explanation. So according to my understanding, 
1) The architectures generated at later epochs are better than the ones generated at the earlier epochs.
2) If I just use the tensorflow graph for the architecture generated by the last epoch and retrain it then it should ideally correspond to the best architecture generated by deep architect.
Hope my understanding is correct.

Best Regards.
Arun

**Comment by negrinho** [comment]
Yes, that is correct, but you need to track performance and pick the best one yourself. If you haven't already, please check the [tutorial](https://github.com/negrinho/deep_architect/blob/master/tutorial.ipynb) for more details. If you read the "Searching the search space" section and then look at the actual implementation of `run_random_searcher` you should get a much better sense on how the searcher, search space, and evaluator interact.

**Comment by DRealArun** [comment]
Thank you very much for the pointers. I will look into them and really nice work !

**Comment by negrinho** [comment]
No worries. We will release a greatly expanded version of DeepArchitect soon (next two weeks or so). You should definitely look into that once it is out. We have been working on it for a while now. It is mostly framework independent (meaning that you can use it with Tensorflow, Pytorch, and other deep learning frameworks). Nonetheless, with this public codebase, you should be able to get decent mileage once you understand the concepts that are covered in the tutorial. I'm closing this issue for now, but feel free to ask follow up questions.

**Comment by DRealArun** [comment]
Have you tried to retrain the .meta file created by deep-architect ? I am facing issues with it . I was able to import the .meta file and get the placeholders. However, when i try to define the Adam optimizer,  it says it is already available in graph. I then tried to get access to the operation of Adam in the graph. After using tf.get_default_graph().get_operation_by_name(), i was able to get hold of the Adam operator. However we i try to de-reference this operator to use the .minimize function, it says minimize is not available. Any help would be appreciated.

**Comment by negrinho** [comment]
I don't have any specific insights regarding this. Do you have a minimal example for the problem? My guess would be that this is not a DeepArchitect specific issue, but rather an idiosyncrasy of how Tensorflow works. Is this the .meta file generated by the checkpointing functionality? I would try to move the instantiation of the [saver](https://github.com/negrinho/deep_architect/blob/master/darch/evaluators.py#L71) after the instantiation of the optimizer (e.g., to line 88 or line 109). Let me know if it solves your problem.

**Comment by DRealArun** [comment]
Yes I feel that this is something which is imposed by tensorflow and not deep architect. However, I just wanted to check,  how did you retrain the generated architectures ?
